workflow: adding default to workflow core and is_update field
inspirehep/backoffice pull request #43
Opened 2024-06-19 07:26 UTC by DonHaul

2024-06-20 04:20 UTC, drjova commented on backoffice/workflows/models.py
> +    is_update = models.BooleanField(default=False)
we have to create also a migration for these :)

2024-06-20 04:21 UTC, drjova requested changes
It's missing the db migration 🙈

2024-06-20 09:09 UTC, DonHaul commented on backoffice/workflows/models.py
> +    is_update = models.BooleanField(default=False)
added :)

2024-06-28 11:09 UTC, DonHaul commented
@drjova it should be good now

2024-06-28 11:10 UTC, drjova approved these changes

2024-06-28 11:11 UTC, merged